#!/usr/bin/env bash
# this bash shell auto generated  by RDP(ratel decompile project) component, do not edit this file
# powered by virjar@RatelGroup"

now_dir=`pwd`
cd `dirname $0`
script_dir=`pwd`
cd ..

rdp_jar=${script_dir}/rdp.jar

if [ -f ${rdp_jar} ] ;then
    echo "use ${rdp_jar}"
else
    echo "can not find rdp jar in path:${rdp_jar}"
    echo -1
fi

cd ${now_dir}
java -jar ${rdp_jar}  $*